# 3rd party modules
import tcod as libtcodpy

# GAME CANVAS
GAME_CANVAS_WIDTH = 800
GAME_CANVAS_HEIGHT = 600
CELL_WIDTH = 16
CELL_HEIGHT = 16

# FPS
FPS_LIMIT = 30

# MAP VARIABLES
MAP_WIDTH = 30
MAP_HEIGHT = 30

# COLORS
COLOR_BLACK = (0, 0, 0)
COLOR_WHITE = (255, 255, 255)
COLOR_GREY = (100, 100, 100)
COLOR_RED = (255, 0, 0)

COLOR_DEFAULT_BACKGROUND = COLOR_GREY

# FIELD OF VIEW
FIELD_OF_VIEW_RADIUS = 10
FIELD_OF_VIEW_LIGHT_WALLS = True
FIELD_OF_VIEW_ALGORITHM = libtcodpy.FOV_BASIC

# MESSAGES
NUM_MESSAGES = 4
